### ISSUE TITLE
Directory "/f1tenth_gym" does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by erquintana** [f1tenth/f1tenth_gym_ros#18]
**Describe the bug**
CMake Error: The source directory "/f1tenth_gym" does not appear to contain CMakeLists.txt. So, when try to execute build_docker instruction, This error is displayed. 

**To Reproduce**
1. Open terminal and Go to 'f1tenth_gym_ros' folder
2. Run 'sudo ./build_docker.sh '
4. See error, CMakeLists.txt is not present on https://github.com/f1tenth/f1tenth_gym

**Expected behavior**
![image](https://user-images.githubusercontent.com/42876141/131397856-5fd97903-74b1-4f80-b645-49bdb4033974.png)

**Comment by hzheng40** [comment]
We're currently updating this to the latest version of f1tenth_gym with the pure python implementation and ros2. For the old cpp backend implementation, switch to the ros1 branch of this repo. Should be fixed by this pr [https://github.com/f1tenth/f1tenth_gym_ros/pull/17](https://github.com/f1tenth/f1tenth_gym_ros/pull/17)
